name: Atom Claim Bot (12hr)

on:
  schedule:
    - cron: '0 */12 * * *'  # UTC 00:00 နဲ့ 12:00
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install aiohttp tqdm
        
    - name: Run Bot
      run: python net.py
      
    - name: Save logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bot-logs
        path: backup_*.json
