name: Atom Claim Bot

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install aiohttp tqdm
      
    - name: Run Bot
      run: python net.py
      
    - name: Upload Output
      uses: actions/upload-artifact@v4
      with:
        name: output-files
        path: |
          output.json
          backup_*.json
